### ISSUE TITLE
Part 1 Step 10 of tutorial fails if nano is not installed

### ISSUE THREAD

**Issue by jeremiah** [kenzanlabs/kubernetes-ci-cd#21]
Maybe use $EDITOR from shell environment instead?

Part 1 Step: 10
Let’s make a change to an HTML file in the cloned project. Running the command below will open /applications/hello-kenzan/index.html in the nano text editor. Change some text inside one of the <p> tags. For example, change “Hello from Kenzan!” to “Hello from Me!”. 
When you’re done, press Ctrl+X to close the file, type Y to confirm the filename, and press Enter to write the changes to the file.
nano applications/hello-kenzan/index.html
Press enter to run the above command for the step. Yes
/bin/sh: 1: nano: not found

/home/jeremiah/GitHub/kubernetes-ci-cd/node_modules/rx-lite/rx.lite.js:81
    throw e;
    ^

Error: Command failed: nano applications/hello-kenzan/index.html
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at AnonymousObserver._onNext (/home/jeremiah/GitHub/kubernetes-ci-cd/start.js:16:13)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/home/jeremiah/GitHub/kubernetes-ci-cd/node_modules/rx/dist/rx.js:1828:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/jeremiah/GitHub/kubernetes-ci-cd/node_modules/rx/dist/rx.js:1762:31)
    at Subject.onNext (/home/jeremiah/GitHub/kubernetes-ci-cd/node_modules/rx/dist/rx.js:5998:19)
    at Subject.tryCatcher (/home/jeremiah/GitHub/kubernetes-ci-cd/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/jeremiah/GitHub/kubernetes-ci-cd/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/jeremiah/GitHub/kubernetes-ci-cd/node_modules/rx/dist/rx.js:1762:31)
    at AutoDetachObserver.tryCatcher (/home/jeremiah/GitHub/kubernetes-ci-cd/node_modules/rx/dist/rx.js:63:31)

npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "part1"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-ci-cd@1.0.0 part1: `node start.js part1.yml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kubernetes-ci-cd@1.0.0 part1 script 'node start.js part1.yml'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kubernetes-ci-cd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node start.js part1.yml
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kubernetes-ci-cd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kubernetes-ci-cd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jeremiah/.npm/_logs/2017-06-19T14_08_19_867Z-debug.log

**Comment by ryandaugherty** [comment]
Hi @jeremiah! Thanks for using the tutorial and taking the time to give us feedback. You raise a fair point in regards to `nano` being uninstalled on some distros. We designed the interactive version to be as streamlined as possible, but didn't account for all cases. We changed our scripts so nano is not required. Thanks again!
